import localFont from "next/font/local";
import "./globals.css";
import ReduxProvider from "@/redux/reduxProvider";
import { Slide, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import AuthWrapper from "@/authWrapper/AuthWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          {/* <AuthWrapper> */}
            <div>{children}</div>
          {/* </AuthWrapper> */}
          <ToastContainer transition={Slide} />
        </ReduxProvider>
      </body>
    </html>
  );
}

// src/app/layout.js
// import ReduxProvider from './ReduxProvider';

// export default function Layout({ children }) {
//   return (
//     <ReduxProvider>
//       <div>{children}</div>
//     </ReduxProvider>
//   );
// }
